# Generated by Django 4.2.13 on 2024-08-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_price_remove_product_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
