# Generated by Django 4.2.13 on 2024-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchase_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.IntegerField(),
        ),
    ]
