# Generated by Django 4.2.13 on 2024-08-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_branchstock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchStock',
        ),
    ]
