# Generated by Django 4.2.13 on 2024-08-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_branchstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='phone_number',
            new_name='contact_info',
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='main.branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='main.branch'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
